ID_LENGTH=14
PATCH_USER_ALLOWED_PROPERTIES=['username', 'name', 'bio']
PATCH_TEAM_ALLOWED_PROPERTIES=['name', 'description']
PATCH_GROUP_ALLOWED_PROPERTIES=['name', 'description']
PATCH_BLOCK_ALLOWED_PROPERTIES=['name', 'description']
PATCH_TASK_ALLOWED_PROPERTIES=['title', 'description', 'block_id', 'position', 'due_at']
PATCH_LABEL_ALLOWED_PROPERTIES=['name', 'color']
ALLOWED_MEMBER_ROLES=['member']
ALLOWED_INVITE_STATUSES=['rejected', 'expired']
AVATAR_PATH='../imgs/avatar/'