ID_LENGTH=14
PATCH_USER_ALLOWED_PROPERTIES=['name']
PATCH_TEAM_ALLOWED_PROPERTIES=['name', 'description']
PATCH_GROUP_ALLOWED_PROPERTIES=['name', 'description']
PATCH_TASK_ALLOWED_PROPERTIES=['title', 'description']